name: Learn basic of GitHub Action

on:
  push:
    branches:
      -  master

jobs:
  helloworld:
    runs-on: ubuntu-latest

    steps:
      - name: print chalo
        run: echo "chalo world !!"

      - name: print hello
        run: echo "hello world !!"
